### PR TITLE
HOTT-2160: Adds smoke tests for search query parser

### PR DESCRIPTION
**Pull request by willfish**
### Jira link

https://transformuk.atlassian.net/browse/HOTT-2160

### What?

I have added/removed/altered:

- Adds package script and smoketests for searchQueryParserSmokeTests
- Adds smoketests directory for all smoke tests
- Update smoketest file references
- Removes duplicate name in directory for beta search

### Why?

I am doing this because:

- This is required to validate changes the get rolled out for the search query parser (see for example: https://github.com/trade-tariff/trade-tariff-search-query-parser/pull/73)

### CODE REVIEW

**Comment by willfish** [comment]
```fish
for script in staging-tariff-frontend-smoketests staging-tariff-backend-smoketests staging-tariff-duty-calculator-smoketests dev-tariff-frontend-smoketests dev-tariff-backend-smoketests dev-tariff-duty-calculator-smoketests dev-tariff-search-query-parser-smoketests
  yarn run $script
end
```

**Comment by willfish** [comment]
Executing all of the scripts runs clean on my local machine using my .env file

**Comment by willfish** [comment]
Running here just fine: https://app.circleci.com/pipelines/github/trade-tariff/trade-tariff-search-query-parser/223/workflows/be284196-510d-4f3d-89c2-dd87b206c6a5/jobs/406

**Review by alexdesi — APPROVED** [review]
it looks good, most of the changes are file renames ✅

**Pull request merged**
